### ISSUE TITLE
Adjustable notification in UCP

### ISSUE THREAD

**Issue by jan-2017** [lassik/phpbb-ext-telegramnotifications#5]
In a large forum, it can happen that the number of notification floods the users. I want an adjustable option for each user in the UCP to select the desired forums for notification separately.That would be a real appreciation of the extension.

**Comment by lassik** [comment]
This would be great, but also a lot of work to do. I'd be happy if somebody else wants to do it.

**Comment by jan-2017** [comment]
That sounds great. The combination of "forum authorization" and "choice of forum notification" makes sense. Unfortunately I'm still in the beginning with the programming language.

**Comment by lassik** [comment]
I will add an ACP option in 0.7.0 to select a user group (discussed in issue #7). Telegram notifications will only be sent about messages visible to that group. So if you want to hide some notifications, you can create a Telegram group and block it from some subforums.

The UCP feature (notifications customizable per user) could probably be done with a lot of effort. However, it would completely change the nature of the extension so I won't do it. (E.g. currently notifications are posted to a Telegram group chat, so it's natural to discuss the forum post in the Telegram group when the group members see the notification. This would not happen naturally if each user received the notification as a private message.)
