### ISSUE TITLE
Reason for the post change

### ISSUE THREAD

**Issue by jan-2017** [lassik/phpbb-ext-telegramnotifications#8]
I have seen the reason for the change of post without the addition "Reason for change" in the messenger notification after the the topic title is displayed.  I think it should be added a hint. For example: Post has been changed - "Reason"

**Comment by lassik** [comment]
I'll add a "reason for change" text to the verbose notifications in the next version.

**Comment by lassik** [comment]
This was implemented in commit 83b35c7.
